# Generated by Django 4.1.2 on 2022-11-06 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.IntegerField(default=0)),
                ('religion', models.IntegerField(default=0)),
                ('wildlife', models.IntegerField(default=0)),
                ('finance', models.IntegerField(default=0)),
                ('nonprofit', models.IntegerField(default=0)),
                ('charity', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('medicine', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isTestData', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('website', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('matchInfo', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('categories', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendUserData', models.BooleanField(default=False)),
                ('viewRadius', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('phone', models.IntegerField()),
                ('interests', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.categories')),
                ('matched', models.ManyToManyField(related_name='matched', to='helpfastapi.organization')),
                ('seen', models.ManyToManyField(related_name='seen', to='helpfastapi.organization')),
                ('settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.preferences')),
            ],
        ),
    ]
