# Generated by Django 4.1.2 on 2022-11-19 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    replaces = [('helpfastapi', '0001_initial'), ('helpfastapi', '0002_profile_delete_user'), ('helpfastapi', '0003_alter_profile_phone'), ('helpfastapi', '0004_alter_profile_phone'), ('helpfastapi', '0005_alter_profile_phone'), ('helpfastapi', '0006_alter_profile_user'), ('helpfastapi', '0007_alter_profile_seen'), ('helpfastapi', '0008_rename_religion_categories_faith_based_and_more'), ('helpfastapi', '0009_rename_matched_profile_matches'), ('helpfastapi', '0010_alter_profile_matches')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.IntegerField(default=0)),
                ('faith_based', models.IntegerField(default=0)),
                ('wildlife', models.IntegerField(default=0)),
                ('finance', models.IntegerField(default=0)),
                ('nonprofit', models.IntegerField(default=0)),
                ('charity', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('health_and_medicine', models.IntegerField(default=0)),
                ('arts_and_culture', models.IntegerField(default=0)),
                ('community', models.IntegerField(default=0)),
                ('disaster_relief', models.IntegerField(default=0)),
                ('education', models.IntegerField(default=0)),
                ('emergency', models.IntegerField(default=0)),
                ('environment', models.IntegerField(default=0)),
                ('family_support', models.IntegerField(default=0)),
                ('housing', models.IntegerField(default=0)),
                ('hunger', models.IntegerField(default=0)),
                ('legal', models.IntegerField(default=0)),
                ('mental_health', models.IntegerField(default=0)),
                ('seniors', models.IntegerField(default=0)),
                ('special_needs', models.IntegerField(default=0)),
                ('sports_and_recreation', models.IntegerField(default=0)),
                ('veterans', models.IntegerField(default=0)),
                ('women', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isTestData', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('website', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('matchInfo', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('categories', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.categories')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendUserData', models.BooleanField(default=False)),
                ('viewRadius', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('interests', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.categories')),
                ('matches', models.ManyToManyField(blank=True, related_name='matches', to='helpfastapi.organization')),
                ('seen', models.ManyToManyField(blank=True, related_name='seenby', to='helpfastapi.organization')),
                ('settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.preferences')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
