# Generated by Django 4.1.2 on 2022-11-08 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpfastapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('phone', models.IntegerField()),
                ('interests', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.categories')),
                ('matched', models.ManyToManyField(blank=True, related_name='matched', to='helpfastapi.organization')),
                ('seen', models.ManyToManyField(blank=True, related_name='seen', to='helpfastapi.organization')),
                ('settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpfastapi.preferences')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
