# Generated by Django 4.1.2 on 2022-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfastapi', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seen',
            field=models.ManyToManyField(blank=True, related_name='seenby', to='helpfastapi.organization'),
        ),
    ]
