# Generated by Django 4.1.2 on 2022-11-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfastapi', '0007_alter_profile_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='religion',
            new_name='faith_based',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='medicine',
            new_name='health_and_medicine',
        ),
        migrations.AddField(
            model_name='categories',
            name='arts_and_culture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='community',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='disaster_relief',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='emergency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='environment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='family_support',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='housing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='hunger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='legal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='mental_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='seniors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='special_needs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='sports_and_recreation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='veterans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='women',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
