# Generated by Django 4.1.2 on 2022-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfastapi', '0009_rename_matched_profile_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matches', to='helpfastapi.organization'),
        ),
    ]
