# Generated by Django 4.1.2 on 2022-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfastapi', '0011_organization_latitude_organization_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Gainesville', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=29.6516),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(default=82.3248),
            preserve_default=False,
        ),
    ]
