# Generated by Django 4.1.2 on 2022-11-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpfastapi', '0012_profile_city_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='location',
        ),
    ]
